- name: Validate role vars
  ansible.builtin.assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Set default targets if none are defined
  when: targets is not defined
  set_fact:
    targets:
      - infrastructure
      - logs

- name: Validate targets
  ansible.builtin.assert:
    that:
      - "target_name_map[item] is defined"
    quiet: true 
  loop: "{{ targets }}"

