---
- name: Check ansible_env for required environment variables
  ansible.builtin.set_fact:
    account_id_is_set: "{{ ansible_env.NEW_RELIC_ACCOUNT_ID is defined }}"
    api_key_is_set: "{{ ansible_env.NEW_RELIC_API_KEY is defined }}"

- name: Check environment for required environment variables
  when: not (account_id_is_set and api_key_is_set)
  loop: "{{ environment }}"
  ansible.builtin.set_fact:
    account_id_is_set: "{{ item.NEW_RELIC_ACCOUNT_ID is defined }}"
    api_key_is_set: "{{ item.NEW_RELIC_API_KEY is defined }}"
  until: account_id_is_set and api_key_is_set
  retries: 0
  no_log: true

- name: Assert required environment variables are set
  ansible.builtin.assert:
    that:
      - account_id_is_set
      - api_key_is_set

- name: Validate role vars
  ansible.builtin.assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Validate targets
  ansible.builtin.assert:
    that:
      - target_name_map[item] is defined
    quiet: true
  loop: "{{ targets }}"
