---
- name: Check ansible_env for required environment variables
  set_fact:
    NEW_RELIC_ACCOUNT_ID_is_set: "{{ ansible_env.NEW_RELIC_ACCOUNT_ID is defined }}"
    NEW_RELIC_API_KEY_is_set: "{{ ansible_env.NEW_RELIC_API_KEY is defined }}"

- name: Check environment for required environment variables
  when: not (NEW_RELIC_ACCOUNT_ID_is_set and NEW_RELIC_API_KEY_is_set)
  loop: "{{ environment }}"
  set_fact:
    NEW_RELIC_ACCOUNT_ID_is_set: "{{ item.NEW_RELIC_ACCOUNT_ID is defined }}"
    NEW_RELIC_API_KEY_is_set: "{{ item.NEW_RELIC_API_KEY is defined }}"
  until: NEW_RELIC_ACCOUNT_ID_is_set and NEW_RELIC_API_KEY_is_set
  retries: 0
  no_log: true

- name: Assert required environment variables are set
  ansible.builtin.assert:
    that:
      - NEW_RELIC_ACCOUNT_ID_is_set
      - NEW_RELIC_API_KEY_is_set

- name: Validate role vars
  ansible.builtin.assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Validate targets
  ansible.builtin.assert:
    that:
      - target_name_map[item] is defined
    quiet: true
  loop: "{{ targets }}"
