---
- name: Validate environment variables on remote host
  ansible.builtin.assert:
    that:
      - ansible_env.NEW_RELIC_ACCOUNT_ID is defined
      - ansible_env.NEW_RELIC_API_KEY is defined
    quiet: true

- name: Note default region if none is set
  when: ansible_env.NEW_RELIC_REGION is not defined
  ansible.builtin.debug:
    msg: "NEW_RELIC_REGION is not set. Defaulting to 'US'"

- name: Validate role vars
  ansible.builtin.assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Validate targets
  ansible.builtin.assert:
    that:
      - target_name_map[item] is defined
    quiet: true
  loop: "{{ targets }}"
